################################# Default configuration ###################
# provide your domain here
baseURL = "https://demo.gethugothemes.com/dot/examplesite/"
# theme
theme = "dot-hugo"
# site title
title = "Dot"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family zhom : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "https://github.com/zhoghub-io"
  
################################ English Language ######################
[Languages.en]
languageName = "English"
languageCode = "en-us"
weight = 1
copyright = "Copyright &copy; 2022 zhoghub All rights reserved."

# banner
[Languages.en.params.banner]
title = "Support Center & Knowledge base"
subtitle = "Find guides, code samples, architectural diagrams, best practices, tutorials, API references, and more to learn how to build on FrogHub."
bg_image = "images/banner.jpg"
placeholder = "Filter to find guides for FrogHub products, services, and APIs."

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Please contact us in the following ways, we will answer the postage price for you as soon as possible."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "contact/"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = ""
weight = 1

[[Languages.en.menu.main]]
name = "Faq"
url = "faq/"
weight = 2

[[Languages.en.menu.main]]
name = "contact"
url = "contact/"
weight = 3

# Dropdown menu
[[Languages.en.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation/"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing/"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features/"
  weight = 3


################################### 中文 Languages ######################
[Languages.zh]
languageName = "中文"
languageCode = "zh_cn"
weight = 2
copyright = "Copyright &copy; 2022 zhoghub All rights reserved."

# banner
[Languages.zh.params.banner]
title = "支持中心 & 知识库"
subtitle = "查找指南、代码示例、架构图、最佳实践、教程、API 参考文档等，了解如何在 FrogHub 上构建应用。"
bg_image = "images/banner.jpg"
placeholder = "进行过滤以查找 FrogHub 产品、服务和 API 的指南。"

# call to action
[Languages.zh.params.cta]
enable = true
title = "没有找到您的想要的答案？"
content = "请通过以下方式联系到我们，我们将尽快邮价为您解答。"
# call to action button
[Languages.zh.params.cta.button]
enable = true
label = "联系我们"
link = "contact/"


################## 中文 navigation #################
[[Languages.zh.menu.main]]
name = "Accueil"
url = "/"
weight = 1

[[Languages.zh.menu.main]]
name = "Faq"
url = "faq/"
weight = 2

[[Languages.zh.menu.main]]
name = "contact"
url = "contact/"
weight = 3

# Dropdown menu
[[Languages.zh.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.zh.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation/"
  weight = 1

  [[Languages.zh.menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing/"
  weight = 2

  [[Languages.zh.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features/"
  weight = 3
